# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CgKaOB0NlJc99UR83sOYzpiaMBqtMtvq
"""

import sys

def formattingOut(output):
    r = ""
    l = ""
    Rc = 0
    for letters in output:
        r += letters
    if len(r) == 5 and Rc < 9:
        r += " "
        l += r
        Rc += 1
        r = ""
    elif len(r) == 5 and Rc == 9:
        l = r + "\n"
        Rc = 0
        r = ""
    return l + r + "\n"

def enc(text, move):
    text = text.upper()
    letters = ""

    for each in text:
        if each.isalpha():
            letters += each
    encoding = []
    for each in text:
        textAsc = ord(each)
        newAsc = textAsc + move
        if newAsc > ord("Z"):
            finalAsc = (newAsc - ord("Z") ) % 26

            if finalAsc == 0:
                result = 26

            newAsc = finalAsc + 64
        encoding.append(chr(newAsc))

    val = "".join(encoding)
    return formattingOut(val)

args = sys.argv

for line in sys.stdin:
    result = enc(line.strip(), int(args[1]))
    sys.stdout.write(result)